SELECT histo_factures.numfac,
       histo_factures.datefac,
       TO_CHAR(datefac, 'MONTH', 'nls_date_language= FRENCH')  MOIS,
       TO_CHAR(datefac, 'RRRR')                                ANNEE,
       HISTO_FACTURES.NUMLIGNE,
       HISTO_FACTURES.TYPEDOC,
       HISTO_FACTURES.CODECLI,
       HISTO_FACTURES.REP,
       HISTO_FACTURES.TOTALHT,
       HISTO_FACTURES.TOTALTVA,
       HISTO_FACTURES.TOTALTTC,
       HISTO_FACTURES.NUMBL,
       HISTO_FACTURES.NUMLIGNE_BL,
       HISTO_FACTURES.REFART,
       DECODE(typedoc, 'FC', qte, - qte)                       QTE,
       DECODE(typedoc, 'FC', volume, - volume)                 VOL,
       HISTO_FACTURES.PU_BRUT,
       HISTO_FACTURES.PU_NET,
       HISTO_FACTURES.FAM1,
       HISTO_FACTURES.FAM2,
       HISTO_FACTURES.FAM3,
       HISTO_FACTURES.FAMART,
       DECODE(typedoc, 'FC', total_ht_ligne, - total_ht_ligne) CA,
       ARTICLES.artgen,
       ZFAMCLI.FAMILLE3_0,
       ARTICLES.artlib,
       BPCUSTOMER.BPCNAM_0,
       BPCUSTOMER.BPCSHO_0
FROM HISTO_FACTURES HISTO_FACTURES,
     ARTICLES ARTICLES,
     BPCUSTOMER BPCUSTOMER,
     ZFAMCLI ZFAMCLI
WHERE HISTO_FACTURES.REFART = ARTICLES.ARTNUM(+)
  AND HISTO_FACTURES.CODECLI = BPCUSTOMER.BPCNUM_0(+)
  AND BPCUSTOMER.BPCNUM_0 = ZFAMCLI.CODE_0(+)
    and (HISTO_FACTURES.DATEFAC BETWEEN to_date('01/01/2018', 'DD/MM/YYYY') AND to_date('30/09/2018', 'DD/MM/YYYY')
              OR HISTO_FACTURES.DATEFAC BETWEEN to_date('01/01/2019', 'DD/MM/YYYY') AND to_date('30/09/2019', 'DD/MM/YYYY'))
  AND HISTO_FACTURES.TYPEDOC <> 'FP'
  AND BPCUSTOMER.TSCCOD_1 = '112'
UNION ALL
SELECT ZCA_HEIMBURGER.NUMFAC,
       ZCA_HEIMBURGER.DATEFAC,
       TO_CHAR(datefac, 'MONTH', 'nls_date_language= FRENCH'),
       TO_CHAR(datefac, 'RRRR'),
       ZCA_HEIMBURGER.NUMLIGNE,
       ZCA_HEIMBURGER.TYPEDOC,
       ZCA_HEIMBURGER.CODECLI,
       ZCA_HEIMBURGER.REP,
       ZCA_HEIMBURGER.TOTALHT,
       ZCA_HEIMBURGER.TOTALTVA,
       ZCA_HEIMBURGER.TOTALTTC,
       ZCA_HEIMBURGER.NUMBL,
       ZCA_HEIMBURGER.NUMLIGNE_BL,
       ZCA_HEIMBURGER.CLE,
       ZCA_HEIMBURGER.QUANTITE,
       ZCA_HEIMBURGER.VOLUME,
       0,
       ZCA_HEIMBURGER.PX_VTE,
       ZCA_HEIMBURGER.FAMART1,
       ZCA_HEIMBURGER.FAMART2,
       ZCA_HEIMBURGER.FAMART3,
       ARTICLES.ARTFAM,
       ZCA_HEIMBURGER.PRIX_NET_ST,
       ARTICLES.artgen,
       ZFAMCLI.FAMILLE3_0,
       ARTICLES.artlib,
       BPCUSTOMER.BPCNAM_0,
       BPCUSTOMER.BPCSHO_0
FROM ZCA_HEIMBURGER ZCA_HEIMBURGER,
     ARTICLES ARTICLES,
     BPCUSTOMER BPCUSTOMER,
     ZFAMCLI ZFAMCLI
WHERE ZCA_HEIMBURGER.CLE = ARTICLES.ARTNUM(+)
  AND ZCA_HEIMBURGER.CODECLI = BPCUSTOMER.BPCNUM_0(+)
  AND BPCUSTOMER.BPCNUM_0 = ZFAMCLI.CODE_0(+)
    and (ZCA_HEIMBURGER.DATEFAC BETWEEN to_date('01/01/2018', 'DD/MM/YYYY') AND to_date('30/09/2018', 'DD/MM/YYYY')
              OR ZCA_HEIMBURGER.DATEFAC BETWEEN to_date('01/01/2019', 'DD/MM/YYYY') AND to_date('30/09/2019', 'DD/MM/YYYY'))
  AND zca_heimburger.typedoc <> 'FP'
  AND bpcustomer.tsccod_1 = '112'
order by 2